In [137]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [138]:
# load the tsv
df = pd.read_csv("data.tsv", sep="\t")

In [139]:
df.head()

,Study ID,Patient ID,Sample ID,Cancer Type,Cancer Type Detailed,Ethnicity,Fraction Genome Altered,Gene Panel,Metastatic Site,MSI Score,...,Primary Tumor Site,Race,Sample Class,Number of Samples Per Patient,Sample coverage,Sample Type,Sex,Somatic Status,TMB (nonsynonymous),Tumor Purity
0,pancreas_msk_2024,P-0000142,P-0000142-T01-IM3,Pancreatic Cancer,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.2681,IMPACT341,NaN,0.00,...,Pancreas,WHITE,Tumor,1,639,Primary,Female,Matched,4.436621,40.0
1,pancreas_msk_2024,P-0002230,P-0002230-T01-IM3,Pancreatic Cancer,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0000,IMPACT341,NaN,0.19,...,Pancreas,WHITE,Tumor,1,701,Primary,Female,Matched,2.218311,50.0
2,pancreas_msk_2024,P-0002704,P-0002704-T01-IM3,Pancreatic Cancer,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0632,IMPACT341,NaN,0.22,...,Pancreas,WHITE,Tumor,1,191,Primary,Female,Matched,0.000000,20.0
3,pancreas_msk_2024,P-0003006,P-0003006-T01-IM3,Pancreatic Cancer,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0000,IMPACT341,NaN,0.00,...,Pancreas,WHITE,Tumor,1,680,Primary,Male,Matched,4.436621,20.0
4,pancreas_msk_2024,P-0003540,P-0003540-T01-IM5,Pancreatic Cancer,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0175,IMPACT410,NaN,0.09,...,Pancreas,WHITE,Tumor,1,409,Primary,Male,Matched,3.914879,20.0

In [140]:
df = df.drop(columns=["Metastatic Site" , "Sample Class"])
df = df.drop(columns=["Patient ID", "Study ID", "Sample ID", "Cancer Type"])
arr = ["Somatic Status", "Number of Samples Per Patient"]
df = df.drop(columns=arr)
df.head()
df.shape

(395, 17)

In [141]:
df.isna().sum()

Cancer Type Detailed          0
Ethnicity                     0
Fraction Genome Altered       0
Gene Panel                    0
MSI Score                     4
MSI Type                      4
Mutation Count               16
Oncotree Code                 0
Overall Survival (Months)     2
Overall Survival Status       0
Primary Tumor Site            0
Race                          0
Sample coverage               0
Sample Type                   0
Sex                           0
TMB (nonsynonymous)           0
Tumor Purity                  4
dtype: int64

In [142]:
df.dtypes

Cancer Type Detailed          object
Ethnicity                     object
Fraction Genome Altered      float64
Gene Panel                    object
MSI Score                    float64
MSI Type                      object
Mutation Count               float64
Oncotree Code                 object
Overall Survival (Months)    float64
Overall Survival Status       object
Primary Tumor Site            object
Race                          object
Sample coverage                int64
Sample Type                   object
Sex                           object
TMB (nonsynonymous)          float64
Tumor Purity                 float64
dtype: object

In [143]:
# fill by median for numeric columns only
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median())
df.isna().sum()

Cancer Type Detailed         0
Ethnicity                    0
Fraction Genome Altered      0
Gene Panel                   0
MSI Score                    0
MSI Type                     4
Mutation Count               0
Oncotree Code                0
Overall Survival (Months)    0
Overall Survival Status      0
Primary Tumor Site           0
Race                         0
Sample coverage              0
Sample Type                  0
Sex                          0
TMB (nonsynonymous)          0
Tumor Purity                 0
dtype: int64

In [144]:
# fill by mode for categorical columns only
categorical_columns = df.select_dtypes(include=['object']).columns
df[categorical_columns] = df[categorical_columns].fillna(df[categorical_columns].mode().iloc[0])
df.isna().sum()

Cancer Type Detailed         0
Ethnicity                    0
Fraction Genome Altered      0
Gene Panel                   0
MSI Score                    0
MSI Type                     0
Mutation Count               0
Oncotree Code                0
Overall Survival (Months)    0
Overall Survival Status      0
Primary Tumor Site           0
Race                         0
Sample coverage              0
Sample Type                  0
Sex                          0
TMB (nonsynonymous)          0
Tumor Purity                 0
dtype: int64

In [145]:
df["Ethnicity"].value_counts()

Ethnicity
Non-Spanish; Non-Hispanic                 367
Spanish  NOS; Hispanic NOS, Latino NOS     11
Unknown whether Spanish or not              8
South/Central America (except Brazil)       3
Dominican Republic                          2
Puerto Rican                                2
Unknown                                     2
Name: count, dtype: int64

In [146]:
# in overall Overall Survival Status , 0 is alive and 1 is dead
# convert to string
df["Overall Survival Status"] = df["Overall Survival Status"].astype(str)

In [147]:
# convert to int
df["Overall Survival Status"] = df["Overall Survival Status"].apply(lambda x: int(x[0]))
df["Overall Survival Status"].value_counts()

Overall Survival Status
1    298
0     97
Name: count, dtype: int64

In [148]:
df.head()

,Cancer Type Detailed,Ethnicity,Fraction Genome Altered,Gene Panel,MSI Score,MSI Type,Mutation Count,Oncotree Code,Overall Survival (Months),Overall Survival Status,Primary Tumor Site,Race,Sample coverage,Sample Type,Sex,TMB (nonsynonymous),Tumor Purity
0,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.2681,IMPACT341,0.00,Stable,4.0,PAAD,8.810862,1,Pancreas,WHITE,639,Primary,Female,4.436621,40.0
1,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0000,IMPACT341,0.19,Stable,2.0,PAAD,3.189006,1,Pancreas,WHITE,701,Primary,Female,2.218311,50.0
2,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0632,IMPACT341,0.22,Stable,3.0,PAAD,5.523227,0,Pancreas,WHITE,191,Primary,Female,0.000000,20.0
3,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0000,IMPACT341,0.00,Stable,4.0,PAAD,12.821777,1,Pancreas,WHITE,680,Primary,Male,4.436621,20.0
4,Pancreatic Adenocarcinoma,Non-Spanish; Non-Hispanic,0.0175,IMPACT410,0.09,Stable,4.0,PAAD,7.199921,1,Pancreas,WHITE,409,Primary,Male,3.914879,20.0

In [149]:
# df = df.drop(columns=["Sample Class"])
df = df.drop(columns=["Primary Tumor Site"])

In [150]:
# one-hot encoding for categorical columns
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

one_categorical_columns = ["Ethnicity" , "Cancer Type Detailed" , "Race" , "Oncotree Code" , "Gene Panel" , "MSI Type"]

# one-hot encoding for categorical columns
one_hot_encoder = OneHotEncoder(drop='first')

# create a column transformer to apply the one-hot encoder to the categorical columns
column_transformer = ColumnTransformer(
    transformers=[
        ('one_hot', one_hot_encoder, one_categorical_columns)
    ],
    remainder='passthrough'  # leave the rest of the columns unchanged
)

# create a pipeline to apply the column transformer to the data
pipeline = Pipeline(steps=[('column_transformer', column_transformer)])

# fit and transform the data using the pipeline
X = pipeline.fit_transform(df)

# get the feature names after one-hot encoding
feature_names = pipeline.named_steps['column_transformer'].get_feature_names_out()

# create a DataFrame with the transformed data and the feature names
X_df = pd.DataFrame(X, columns=feature_names)

# add the target variable to the DataFrame
y_df = df["Overall Survival Status"].reset_index(drop=True)
X_df["Overall Survival Status"] = y_df

In [155]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Encode the target variable

# X_df["remainder__Sample Type"] = le.fit_transform(X_df["remainder__Sample Type"])
X_df["remainder__Sex"] = le.fit_transform(X_df["remainder__Sex"])

In [157]:
# print first element from each column

X_df.iloc[0, :]
# X_df.head()

one_hot__Ethnicity_Non-Spanish; Non-Hispanic                                     1.0
one_hot__Ethnicity_Puerto Rican                                                  0.0
one_hot__Ethnicity_South/Central America (except Brazil)                         0.0
one_hot__Ethnicity_Spanish  NOS; Hispanic NOS, Latino NOS                        0.0
one_hot__Ethnicity_Unknown                                                       0.0
one_hot__Ethnicity_Unknown whether Spanish or not                                0.0
one_hot__Cancer Type Detailed_Adenosquamous Carcinoma of the Pancreas            0.0
one_hot__Cancer Type Detailed_Cancer of Unknown Primary                          0.0
one_hot__Cancer Type Detailed_Intraductal Papillary Mucinous Neoplasm            0.0
one_hot__Cancer Type Detailed_Pancreatic Adenocarcinoma                          1.0
one_hot__Cancer Type Detailed_Undifferentiated Carcinoma of the Pancreas         0.0
one_hot__Race_BLACK OR AFRICAN AMERICAN                                          0.0
one_hot__Race_NATIVE AMERICAN-AM IND/ALASKA                                      0.0
one_hot__Race_OTHER                                                              0.0
one_hot__Race_PT REFUSED TO ANSWER                                               0.0
one_hot__Race_WHITE                                                              1.0
one_hot__Oncotree Code_IPMN                                                      0.0
one_hot__Oncotree Code_PAAC                                                      0.0
one_hot__Oncotree Code_PAAD                                                      1.0
one_hot__Oncotree Code_PAASC                                                     0.0
one_hot__Oncotree Code_UCP                                                       0.0
one_hot__Gene Panel_IMPACT410                                                    0.0
one_hot__Gene Panel_IMPACT468                                                    0.0
one_hot__MSI Type_Indeterminate                                                  0.0
one_hot__MSI Type_Instable                                                       0.0
one_hot__MSI Type_Stable                                                         1.0
remainder__Fraction Genome Altered                                            0.2681
remainder__MSI Score                                                             0.0
remainder__Mutation Count                                                        4.0
remainder__Overall Survival (Months)                                        8.810862
remainder__Overall Survival Status                                                 1
remainder__Sample coverage                                                       639
remainder__Sample Type                                                             1
remainder__Sex                                                                     0
remainder__TMB (nonsynonymous)                                              4.436621
remainder__Tumor Purity                                                         40.0
Overall Survival Status                                                            1
Name: 0, dtype: object

In [158]:
# convrt to csv
X_df.to_csv("data_encoded.csv", index=False)
# check the shape of the data   
X_df.shape

(395, 37)